# Generated by Django 3.2 on 2021-04-28 20:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkModel',
            fields=[
                ('destination', models.URLField()),
                ('token', models.CharField(default=uuid.uuid4, max_length=6, primary_key=True, serialize=False)),
            ],
        ),
    ]
