# Generated by Django 3.2 on 2021-04-28 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listlinks', '0003_alter_linkmodel_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinkModel',
        ),
    ]
